package routes

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"

	_ "github.com/tempfiles-Team/tempfiles-backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// SwaggerRoute func for describe group of API Docs routes.
func SwaggerRoute(r fiber.Router) {
	route := r.Group("/swagger")

	route.Get("*", swagger.HandlerDefault)
}
